# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/nativ

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/nativ

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /workspaces/nativ/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/nativ/CMakeFiles /workspaces/nativ//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/nativ/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named navit

# Build rule for target.
navit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 navit
.PHONY : navit

# fast build rule for target.
navit/fast:
	$(MAKE) $(MAKESILENT) -f navit/CMakeFiles/navit.dir/build.make navit/CMakeFiles/navit.dir/build
.PHONY : navit/fast

# Manual pre-install relink rule for target.
navit/preinstall:
	$(MAKE) $(MAKESILENT) -f navit/CMakeFiles/navit.dir/build.make navit/CMakeFiles/navit.dir/preinstall
.PHONY : navit/preinstall

#=============================================================================
# Target rules for targets named navit_core

# Build rule for target.
navit_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 navit_core
.PHONY : navit_core

# fast build rule for target.
navit_core/fast:
	$(MAKE) $(MAKESILENT) -f navit/CMakeFiles/navit_core.dir/build.make navit/CMakeFiles/navit_core.dir/build
.PHONY : navit_core/fast

#=============================================================================
# Target rules for targets named navit_config_xml_resource

# Build rule for target.
navit_config_xml_resource: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 navit_config_xml_resource
.PHONY : navit_config_xml_resource

# fast build rule for target.
navit_config_xml_resource/fast:
	$(MAKE) $(MAKESILENT) -f navit/CMakeFiles/navit_config_xml_resource.dir/build.make navit/CMakeFiles/navit_config_xml_resource.dir/build
.PHONY : navit_config_xml_resource/fast

#=============================================================================
# Target rules for targets named locale_resource

# Build rule for target.
locale_resource: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 locale_resource
.PHONY : locale_resource

# fast build rule for target.
locale_resource/fast:
	$(MAKE) $(MAKESILENT) -f navit/CMakeFiles/locale_resource.dir/build.make navit/CMakeFiles/locale_resource.dir/build
.PHONY : locale_resource/fast

#=============================================================================
# Target rules for targets named navit_config_xml

# Build rule for target.
navit_config_xml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 navit_config_xml
.PHONY : navit_config_xml

# fast build rule for target.
navit_config_xml/fast:
	$(MAKE) $(MAKESILENT) -f navit/CMakeFiles/navit_config_xml.dir/build.make navit/CMakeFiles/navit_config_xml.dir/build
.PHONY : navit_config_xml/fast

#=============================================================================
# Target rules for targets named support_zlib

# Build rule for target.
support_zlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 support_zlib
.PHONY : support_zlib

# fast build rule for target.
support_zlib/fast:
	$(MAKE) $(MAKESILENT) -f navit/support/zlib/CMakeFiles/support_zlib.dir/build.make navit/support/zlib/CMakeFiles/support_zlib.dir/build
.PHONY : support_zlib/fast

#=============================================================================
# Target rules for targets named support_libpng

# Build rule for target.
support_libpng: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 support_libpng
.PHONY : support_libpng

# fast build rule for target.
support_libpng/fast:
	$(MAKE) $(MAKESILENT) -f navit/support/libpng/CMakeFiles/support_libpng.dir/build.make navit/support/libpng/CMakeFiles/support_libpng.dir/build
.PHONY : support_libpng/fast

#=============================================================================
# Target rules for targets named support_wordexp

# Build rule for target.
support_wordexp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 support_wordexp
.PHONY : support_wordexp

# fast build rule for target.
support_wordexp/fast:
	$(MAKE) $(MAKESILENT) -f navit/support/wordexp/CMakeFiles/support_wordexp.dir/build.make navit/support/wordexp/CMakeFiles/support_wordexp.dir/build
.PHONY : support_wordexp/fast

#=============================================================================
# Target rules for targets named support_gettext_intl

# Build rule for target.
support_gettext_intl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 support_gettext_intl
.PHONY : support_gettext_intl

# fast build rule for target.
support_gettext_intl/fast:
	$(MAKE) $(MAKESILENT) -f navit/support/gettext_intl/CMakeFiles/support_gettext_intl.dir/build.make navit/support/gettext_intl/CMakeFiles/support_gettext_intl.dir/build
.PHONY : support_gettext_intl/fast

#=============================================================================
# Target rules for targets named libintl.h

# Build rule for target.
libintl.h: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libintl.h
.PHONY : libintl.h

# fast build rule for target.
libintl.h/fast:
	$(MAKE) $(MAKESILENT) -f navit/support/gettext_intl/CMakeFiles/libintl.h.dir/build.make navit/support/gettext_intl/CMakeFiles/libintl.h.dir/build
.PHONY : libintl.h/fast

#=============================================================================
# Target rules for targets named support_shapefile

# Build rule for target.
support_shapefile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 support_shapefile
.PHONY : support_shapefile

# fast build rule for target.
support_shapefile/fast:
	$(MAKE) $(MAKESILENT) -f navit/support/shapefile/CMakeFiles/support_shapefile.dir/build.make navit/support/shapefile/CMakeFiles/support_shapefile.dir/build
.PHONY : support_shapefile/fast

#=============================================================================
# Target rules for targets named graphics_svg_debug

# Build rule for target.
graphics_svg_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graphics_svg_debug
.PHONY : graphics_svg_debug

# fast build rule for target.
graphics_svg_debug/fast:
	$(MAKE) $(MAKESILENT) -f navit/graphics/svg_debug/CMakeFiles/graphics_svg_debug.dir/build.make navit/graphics/svg_debug/CMakeFiles/graphics_svg_debug.dir/build
.PHONY : graphics_svg_debug/fast

#=============================================================================
# Target rules for targets named speech_cmdline

# Build rule for target.
speech_cmdline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 speech_cmdline
.PHONY : speech_cmdline

# fast build rule for target.
speech_cmdline/fast:
	$(MAKE) $(MAKESILENT) -f navit/speech/cmdline/CMakeFiles/speech_cmdline.dir/build.make navit/speech/cmdline/CMakeFiles/speech_cmdline.dir/build
.PHONY : speech_cmdline/fast

#=============================================================================
# Target rules for targets named graphics_null

# Build rule for target.
graphics_null: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graphics_null
.PHONY : graphics_null

# fast build rule for target.
graphics_null/fast:
	$(MAKE) $(MAKESILENT) -f navit/graphics/null/CMakeFiles/graphics_null.dir/build.make navit/graphics/null/CMakeFiles/graphics_null.dir/build
.PHONY : graphics_null/fast

#=============================================================================
# Target rules for targets named osd_core

# Build rule for target.
osd_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 osd_core
.PHONY : osd_core

# fast build rule for target.
osd_core/fast:
	$(MAKE) $(MAKESILENT) -f navit/osd/core/CMakeFiles/osd_core.dir/build.make navit/osd/core/CMakeFiles/osd_core.dir/build
.PHONY : osd_core/fast

#=============================================================================
# Target rules for targets named vehicle_demo

# Build rule for target.
vehicle_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vehicle_demo
.PHONY : vehicle_demo

# fast build rule for target.
vehicle_demo/fast:
	$(MAKE) $(MAKESILENT) -f navit/vehicle/demo/CMakeFiles/vehicle_demo.dir/build.make navit/vehicle/demo/CMakeFiles/vehicle_demo.dir/build
.PHONY : vehicle_demo/fast

#=============================================================================
# Target rules for targets named vehicle_file

# Build rule for target.
vehicle_file: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vehicle_file
.PHONY : vehicle_file

# fast build rule for target.
vehicle_file/fast:
	$(MAKE) $(MAKESILENT) -f navit/vehicle/file/CMakeFiles/vehicle_file.dir/build.make navit/vehicle/file/CMakeFiles/vehicle_file.dir/build
.PHONY : vehicle_file/fast

#=============================================================================
# Target rules for targets named vehicle_pipe

# Build rule for target.
vehicle_pipe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vehicle_pipe
.PHONY : vehicle_pipe

# fast build rule for target.
vehicle_pipe/fast:
	$(MAKE) $(MAKESILENT) -f navit/vehicle/file/CMakeFiles/vehicle_pipe.dir/build.make navit/vehicle/file/CMakeFiles/vehicle_pipe.dir/build
.PHONY : vehicle_pipe/fast

#=============================================================================
# Target rules for targets named vehicle_serial

# Build rule for target.
vehicle_serial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vehicle_serial
.PHONY : vehicle_serial

# fast build rule for target.
vehicle_serial/fast:
	$(MAKE) $(MAKESILENT) -f navit/vehicle/file/CMakeFiles/vehicle_serial.dir/build.make navit/vehicle/file/CMakeFiles/vehicle_serial.dir/build
.PHONY : vehicle_serial/fast

#=============================================================================
# Target rules for targets named vehicle_socket

# Build rule for target.
vehicle_socket: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vehicle_socket
.PHONY : vehicle_socket

# fast build rule for target.
vehicle_socket/fast:
	$(MAKE) $(MAKESILENT) -f navit/vehicle/file/CMakeFiles/vehicle_socket.dir/build.make navit/vehicle/file/CMakeFiles/vehicle_socket.dir/build
.PHONY : vehicle_socket/fast

#=============================================================================
# Target rules for targets named gui_internal

# Build rule for target.
gui_internal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gui_internal
.PHONY : gui_internal

# fast build rule for target.
gui_internal/fast:
	$(MAKE) $(MAKESILENT) -f navit/gui/internal/CMakeFiles/gui_internal.dir/build.make navit/gui/internal/CMakeFiles/gui_internal.dir/build
.PHONY : gui_internal/fast

#=============================================================================
# Target rules for targets named map_binfile

# Build rule for target.
map_binfile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 map_binfile
.PHONY : map_binfile

# fast build rule for target.
map_binfile/fast:
	$(MAKE) $(MAKESILENT) -f navit/map/binfile/CMakeFiles/map_binfile.dir/build.make navit/map/binfile/CMakeFiles/map_binfile.dir/build
.PHONY : map_binfile/fast

#=============================================================================
# Target rules for targets named map_filter

# Build rule for target.
map_filter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 map_filter
.PHONY : map_filter

# fast build rule for target.
map_filter/fast:
	$(MAKE) $(MAKESILENT) -f navit/map/filter/CMakeFiles/map_filter.dir/build.make navit/map/filter/CMakeFiles/map_filter.dir/build
.PHONY : map_filter/fast

#=============================================================================
# Target rules for targets named map_mg

# Build rule for target.
map_mg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 map_mg
.PHONY : map_mg

# fast build rule for target.
map_mg/fast:
	$(MAKE) $(MAKESILENT) -f navit/map/mg/CMakeFiles/map_mg.dir/build.make navit/map/mg/CMakeFiles/map_mg.dir/build
.PHONY : map_mg/fast

#=============================================================================
# Target rules for targets named map_shapefile

# Build rule for target.
map_shapefile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 map_shapefile
.PHONY : map_shapefile

# fast build rule for target.
map_shapefile/fast:
	$(MAKE) $(MAKESILENT) -f navit/map/shapefile/CMakeFiles/map_shapefile.dir/build.make navit/map/shapefile/CMakeFiles/map_shapefile.dir/build
.PHONY : map_shapefile/fast

# Manual pre-install relink rule for target.
map_shapefile/preinstall:
	$(MAKE) $(MAKESILENT) -f navit/map/shapefile/CMakeFiles/map_shapefile.dir/build.make navit/map/shapefile/CMakeFiles/map_shapefile.dir/preinstall
.PHONY : map_shapefile/preinstall

#=============================================================================
# Target rules for targets named map_textfile

# Build rule for target.
map_textfile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 map_textfile
.PHONY : map_textfile

# fast build rule for target.
map_textfile/fast:
	$(MAKE) $(MAKESILENT) -f navit/map/textfile/CMakeFiles/map_textfile.dir/build.make navit/map/textfile/CMakeFiles/map_textfile.dir/build
.PHONY : map_textfile/fast

#=============================================================================
# Target rules for targets named map_csv

# Build rule for target.
map_csv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 map_csv
.PHONY : map_csv

# fast build rule for target.
map_csv/fast:
	$(MAKE) $(MAKESILENT) -f navit/map/csv/CMakeFiles/map_csv.dir/build.make navit/map/csv/CMakeFiles/map_csv.dir/build
.PHONY : map_csv/fast

#=============================================================================
# Target rules for targets named traffic_dummy

# Build rule for target.
traffic_dummy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 traffic_dummy
.PHONY : traffic_dummy

# fast build rule for target.
traffic_dummy/fast:
	$(MAKE) $(MAKESILENT) -f navit/traffic/dummy/CMakeFiles/traffic_dummy.dir/build.make navit/traffic/dummy/CMakeFiles/traffic_dummy.dir/build
.PHONY : traffic_dummy/fast

#=============================================================================
# Target rules for targets named traffic_null

# Build rule for target.
traffic_null: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 traffic_null
.PHONY : traffic_null

# fast build rule for target.
traffic_null/fast:
	$(MAKE) $(MAKESILENT) -f navit/traffic/null/CMakeFiles/traffic_null.dir/build.make navit/traffic/null/CMakeFiles/traffic_null.dir/build
.PHONY : traffic_null/fast

#=============================================================================
# Target rules for targets named fib

# Build rule for target.
fib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fib
.PHONY : fib

# fast build rule for target.
fib/fast:
	$(MAKE) $(MAKESILENT) -f navit/fib-1.1/CMakeFiles/fib.dir/build.make navit/fib-1.1/CMakeFiles/fib.dir/build
.PHONY : fib/fast

#=============================================================================
# Target rules for targets named images

# Build rule for target.
images: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 images
.PHONY : images

# fast build rule for target.
images/fast:
	$(MAKE) $(MAKESILENT) -f navit/icons/CMakeFiles/images.dir/build.make navit/icons/CMakeFiles/images.dir/build
.PHONY : images/fast

#=============================================================================
# Target rules for targets named images_resource

# Build rule for target.
images_resource: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 images_resource
.PHONY : images_resource

# fast build rule for target.
images_resource/fast:
	$(MAKE) $(MAKESILENT) -f navit/icons/CMakeFiles/images_resource.dir/build.make navit/icons/CMakeFiles/images_resource.dir/build
.PHONY : images_resource/fast

#=============================================================================
# Target rules for targets named textures

# Build rule for target.
textures: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 textures
.PHONY : textures

# fast build rule for target.
textures/fast:
	$(MAKE) $(MAKESILENT) -f navit/textures/CMakeFiles/textures.dir/build.make navit/textures/CMakeFiles/textures.dir/build
.PHONY : textures/fast

#=============================================================================
# Target rules for targets named textures_resource

# Build rule for target.
textures_resource: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 textures_resource
.PHONY : textures_resource

# fast build rule for target.
textures_resource/fast:
	$(MAKE) $(MAKESILENT) -f navit/textures/CMakeFiles/textures_resource.dir/build.make navit/textures/CMakeFiles/textures_resource.dir/build
.PHONY : textures_resource/fast

#=============================================================================
# Target rules for targets named sample_map

# Build rule for target.
sample_map: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sample_map
.PHONY : sample_map

# fast build rule for target.
sample_map/fast:
	$(MAKE) $(MAKESILENT) -f navit/maps/CMakeFiles/sample_map.dir/build.make navit/maps/CMakeFiles/sample_map.dir/build
.PHONY : sample_map/fast

#=============================================================================
# Target rules for targets named locales

# Build rule for target.
locales: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 locales
.PHONY : locales

# fast build rule for target.
locales/fast:
	$(MAKE) $(MAKESILENT) -f po/CMakeFiles/locales.dir/build.make po/CMakeFiles/locales.dir/build
.PHONY : locales/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... images"
	@echo "... images_resource"
	@echo "... libintl.h"
	@echo "... locale_resource"
	@echo "... locales"
	@echo "... navit_config_xml"
	@echo "... navit_config_xml_resource"
	@echo "... sample_map"
	@echo "... textures"
	@echo "... textures_resource"
	@echo "... fib"
	@echo "... graphics_null"
	@echo "... graphics_svg_debug"
	@echo "... gui_internal"
	@echo "... map_binfile"
	@echo "... map_csv"
	@echo "... map_filter"
	@echo "... map_mg"
	@echo "... map_shapefile"
	@echo "... map_textfile"
	@echo "... navit"
	@echo "... navit_core"
	@echo "... osd_core"
	@echo "... speech_cmdline"
	@echo "... support_gettext_intl"
	@echo "... support_libpng"
	@echo "... support_shapefile"
	@echo "... support_wordexp"
	@echo "... support_zlib"
	@echo "... traffic_dummy"
	@echo "... traffic_null"
	@echo "... vehicle_demo"
	@echo "... vehicle_file"
	@echo "... vehicle_pipe"
	@echo "... vehicle_serial"
	@echo "... vehicle_socket"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

