# Install script for directory: /workspaces/nativ/po

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "RelWithDebInfo")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/i686-w64-mingw32-objdump")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/af/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/af.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/ar/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/ar.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/ast/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/ast.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/be/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/be.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/bg/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/bg.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/bs/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/bs.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/ca/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/ca.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/ckb/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/ckb.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/cs/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/cs.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/cy/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/cy.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/da/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/da.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/de/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/de.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/de_CH/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/de_CH.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/el/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/el.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/en/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/en.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/en_AU/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/en_AU.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/en_CA/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/en_CA.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/en_GB/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/en_GB.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/eo/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/eo.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/es/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/es.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/et/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/et.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/eu/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/eu.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/fa/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/fa.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/fi/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/fi.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/fil/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/fil.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/fo/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/fo.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/fr/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/fr.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/fr_CH/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/fr_CH.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/fy/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/fy.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/gl/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/gl.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/he/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/he.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/hi/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/hi.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/hr/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/hr.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/hu/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/hu.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/id/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/id.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/it/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/it.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/ja/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/ja.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/jv/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/jv.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/kk/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/kk.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/kn/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/kn.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/ko/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/ko.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/ku/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/ku.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/lb/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/lb.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/lt/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/lt.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/lv/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/lv.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/mk/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/mk.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/ml/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/ml.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/mn/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/mn.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/mr/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/mr.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/nb/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/nb.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/nds/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/nds.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/nl/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/nl.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/nn/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/nn.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/pl/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/pl.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/pms/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/pms.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/pt/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/pt.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/pt_BR/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/pt_BR.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/ro/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/ro.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/ru/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/ru.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/sc/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/sc.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/si/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/si.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/sk/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/sk.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/sl/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/sl.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/sq/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/sq.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/sr/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/sr.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/sv/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/sv.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/sw/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/sw.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/ta/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/ta.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/te/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/te.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/th/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/th.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/tr/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/tr.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/uk/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/uk.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/ur/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/ur.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/vi/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/vi.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/zh_CN/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/zh_CN.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/zh_HK/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/zh_HK.mo")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/locale/zh_TW/LC_MESSAGES" TYPE FILE RENAME "navit.mo" FILES "/workspaces/nativ/win32/po/zh_TW.mo")
endif()

